package com.lll.greendaodemo;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.shopcardemo.bean.ShopCarBean;
import com.bawei.shopcardemo.bean.User;

import com.lll.greendaodemo.ShopCarBeanDao;
import com.lll.greendaodemo.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopCarBeanDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ShopCarBeanDao shopCarBeanDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopCarBeanDaoConfig = daoConfigMap.get(ShopCarBeanDao.class).clone();
        shopCarBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        shopCarBeanDao = new ShopCarBeanDao(shopCarBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(ShopCarBean.class, shopCarBeanDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        shopCarBeanDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ShopCarBeanDao getShopCarBeanDao() {
        return shopCarBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
